name: Daily Option Walls Update

on:
  push:
    branches:
      - main
  schedule:
    # Runs at 18:00 UTC on Sun, Mon, Tue, Wed, Thu
    - cron: '0 2 * * 1-5'
  workflow_dispatch:  # allows manual trigger

jobs:
  build-and-update-walls:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance numpy scipy pandas

    - name: Run get_walls.py
      run: |
        python options/get_walls.py

    - name: Commit and push updated walls.js
      env:
        PAT: ${{ secrets.PINESCRIPT_LIBS_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add options/walls.js
        git diff --cached --quiet || git commit -m "Update walls.js [skip ci]"
        git push https://x-access-token:${PAT}@github.com/paulcwarren/pinescript-libs.git HEAD:main

    # - name: Commit and push updated walls.js
    #   run: |
    #     git config --global user.name "github-actions[bot]"
    #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
    #     git add options/walls.js
    #     git diff --cached --quiet || git commit -m "Update walls.js [skip ci]"
    #     git push
